<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>60a1f306-f4da-4408-96c7-4c12763777fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AJOCNS.Domain\AJOCNS.Domain.csproj" />
    <ProjectReference Include="..\AJOCNS.Shared\AJOCNS.Shared.csproj" />
  </ItemGroup>

</Project>
